title: "Dr. med. Helene Torabi-Tillig"
description: "Psychotherapeutische Praxis in Berlin"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Site settings
lang: de
author: "Dr. med. Helene Torabi-Tillig"
email: 
phone: 
address: "Schlieperstr. 69, 13507 Berlin"

# Navigation
header_pages:
  - about.md
  - services.md
  - contact.md