title: "Dr. med. Helene Torabi-Tillig"
description: "Psychotherapeutische Praxis in Berlin"
baseurl: "https://ramintorabi.github.io/psychotherapie-torabi-tillig/"
url: "https://ramintorabi.github.io/psychotherapie-torabi-tillig/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Site settings
lang: de
author: "Dr. med. Helene Torabi-Tillig"
email: 
phone: +49 30 54490427
address: "Schlieperstr. 69, 13507 Berlin"
